school-ru/protected/controllers/TeacherController.php
<?php

class TeacherController extends Controller
{

	/**
	 * Весь список
	 */
	public function actionIndex() {
		$teacher = new Teacher('search');
		$teacher->unsetAttributes();
		if (isset($_GET['Teacher'])) {
			$teacher->attributes = $_GET['Teacher'];
		}

		$this->render('index', array(
			'teacher' => $teacher,
		));
	}

	/**
	 * Добавление учителя
	 */
	public function actionCreate() {
		$teacher = new Teacher;
		$student = Student::model()->findAll();

		if (isset($_POST['Teacher'])) {
			$teacher->attributes = $_POST['Teacher'];
			$teacher->student    = $_POST['student'];

			if ($teacher->save()) {
				$this->redirect(array('/teacher'));
			}
		}

		$this->render('create', array(
			'teacher' => $teacher,
			'student' => $student,
		));
	}

	/**
	 * Редактирование учителя
	 * @param int $id
	 */
	public function actionUpdate($id) {
		$teacher = Teacher::model()->with(array('students'))->findByPk($id);
		$student = Student::model()->findAll();

		if (isset($_POST['Teacher'])) {
			$teacher->attributes = $_POST['Teacher'];
			$teacher->student    = $_POST['student'];

			if ($teacher->save()) {
				$this->redirect(array('/teacher'));
			}
		}

		$this->render('update', array(
			'teacher' => $teacher,
			'student' => $student,
		));
	}

	/**
	 * Удаление
	 * @param int $id
	 */
	public function actionDelete($id) {
		$this->loadModel($id)->delete();

		if (!isset($_GET['ajax'])) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
	}

	/**
	 * Списки учителей с фильтром
	 */
	public function actionSpec() {
		$spec = Teacher::model()->findAllBySpec();
		$best = Teacher::model()->findAllByBest();

		$this->render('spec', array(
			'spec' => $spec,
			'best' => $best,
		));
	}

	/**
	 * Загружаем модель, либо эксэпшн
	 * @param int $id
	 * @return mixed
	 * @throws CHttpException
	 */
	public function loadModel($id) {
		$model = Teacher::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'Не найдена страница.');
		}
		return $model;
	}

}

school-ru/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="en">

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Учителя', 'url'=>array('/teacher')),
				array('label'=>'Учинеки', 'url'=>array('/student')),
				array('label'=>'Спец. учителя', 'url'=>array('/teacher/spec')),
			),
		)); ?>
	</div><!-- mainmenu -->

	<div id="content">
		<?php echo $content; ?>
	</div>

	<div class="clear"></div>

	<div id="footer">
		Копирайты
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>